# -*- coding: utf-8 -*-
"""Program.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DsD8qNjz32yjNofy2CjMJt0P_NoXJg1t
"""

def maximum_value(lst):
    return max(lst)

def minimum_value(lst):
    return min(lst)

def sort_list_ascending(lst):
    return sorted(lst)

def is_perfect_square(number):
    square_root = number ** 0.5
    return square_root.is_integer()

# maximum value in a list
numbers = [10, 5, 8, 20, 3]
maximum_value = maximum_value(numbers)
print("Maximum value in the list:", maximum_value)

# minimum value in a list
minimum_value = minimum_value(numbers)
print("Minimum value in the list:", minimum_value)

# Sorting a list in ascending order
sorted_list = sort_list_ascending(numbers)
print("Original List:", numbers)
print("Sorted List:", sorted_list)

# Checking if a number is a perfect square
number = 50
if is_perfect_square(number):
    print(number, "is a perfect square.")
else:
    print(number, "is not a perfect square.")